#jad.config.overrideAll=true
jad.telnetPort=3658
jad.httpPort=8563
jad.ip=127.0.0.1

# seconds
jad.sessionTimeout=1800

#jad.enhanceLoaders=java.lang.ClassLoader

# https://github.com/Akshita-Sahu/JAD/doc/en/auth
# jad.username=jad
# jad.password=jad

# local connection non auth, like telnet 127.0.0.1 3658
jad.localConnectionNonAuth=true

#jad.appName=demoapp
#jad.tunnelServer=ws://127.0.0.1:7777/ws
#jad.agentId=mmmmmmyiddddd

#jad.disabledCommands=stop,dump

#jad.outputPath=jad-output

# MCP (Model Context Protocol) configuration
jad.mcpEndpoint=/mcp
jad.mcpProtocol=STREAMABLE
