# jad tunnel server host
jad.server.host=0.0.0.0
# jad tunnel server port
jad.server.port=7777

# for all endpoints
management.endpoints.web.exposure.include=*

# default user name
spring.security.user.name=jad

# If set to true, be sure to do security protection to ensure that the server will not be illegally accessed
jad.enable-detail-pages=false

spring.cache.type=caffeine
spring.cache.cache-names=inMemoryClusterCache
spring.cache.caffeine.spec=maximumSize=3000,expireAfterAccess=3600s

#jad.embedded-redis.enabled=true
#jad.embedded-redis.settings=maxmemory 128M
#spring.redis.host=127.0.0.1
